---
title: "Tortuosity analysis of cauterized mutants"
author: "Bruno C. Vellutini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
creation: May 26, 2021
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, cache = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/Projects/Cephalic_furrow/7-Paper/1-analyses/germband-cauterizations")
library(ggplot2)
library(ggbeeswarm)
```

## Load measurements

```{r load}
# Get list of measurement files
datafiles <- list.files(path = "3-tortuosity", pattern = "*.txt")

# Create placeholder dataframe for all datasets
datasets <- data.frame()

# Datasets to be skipped due to artifacts
discard <- c(
  "STR_DUP_btd_dorsal_cauterized_homozygous_2021-03-04_E1_equator.1.txt" # Dirt on surface
)

# Loop over datafiles
for (d in 1:length(datafiles)) {
  # Filename
  dataname <- datafiles[d]
  if (dataname %in% discard) {
    next
  }
  # Import data excluding additional lines (nrow > 20)
  tmpdata <- read.delim(paste0("3-tortuosity/", dataname), nrows = 20)
  # Create dataframe
  tmpdf <- data.frame(
    timepoint=paste0("TP", sprintf("%02d", tmpdata$Skeleton.ID)),
    minute=(tmpdata$Skeleton.ID - 1) * 2.63,
    length=tmpdata$Branch.length,
    tortuosity=tmpdata$Branch.length / tmpdata$Euclidean.distance,
    delta_length=(tmpdata$Branch.length - tmpdata$Branch.length[1])
    )
  # Split filename to parse variables
  namesplit <- strsplit(dataname, "_")
  stock <- namesplit[[1]][3]
  sample <- namesplit[[1]][5]
  embryo <- paste(namesplit[[1]][7], namesplit[[1]][8], sep = "_")
  sidestr <- namesplit[[1]][9]
  if (sidestr == "equator.1.txt") {
    side <- "right"
  } else if (sidestr == "equator.2.txt") {
    side <- "left"
  }
  # Add variables as columns
  tmpdf$stock <- stock
  tmpdf$sample <- sample
  tmpdf$embryo <- embryo
  tmpdf$side <- side
  # Bind to placeholder dataframe
  datasets <- rbind(datasets, tmpdf)
}

```
## Print summary

```{r summary}
print_stats <- function(dataframe, stock, sample) {
  filter_df <- (dataframe$stock == stock & dataframe$sample == sample)
  df <- dataframe[filter_df,]
  df <- droplevels(df)

  # Define row
  row <- c(stock,
           sample,
           length(unique(df[,c("embryo", "side")])$embryo),
           length(unique(df$embryo))
           )
  
  return(row)
}

# Save stats to data frame
stats <- data.frame()

# Bind row by row
stats <- rbind(stats, print_stats(datasets, "btd", "control"))
stats <- rbind(stats, print_stats(datasets, "btd", "cauterized"))
stats <- rbind(stats, print_stats(datasets, "eve", "control"))
stats <- rbind(stats, print_stats(datasets, "eve", "cauterized"))

# Add column names
colnames(stats) <- c("stock", "sample", "n_folds", "n_embryos")

# Convert columns to numeric
stats[, 3:4] <- apply(stats[, 3:4], 2, as.numeric)

# Write table to file
write.table(format(stats, digits=2), file = "tort-stats.txt", quote = FALSE, row.names = FALSE, sep = "\t")
print(stats)
```


## Plot tortuosity boxplot

```{r facet-boxplot}
# Plot stocks separately using bars side by side
ggplot(datasets, aes(minute, tortuosity, fill = sample, group = interaction(minute, sample))) +
  geom_boxplot(aes(color = sample), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.7, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 1, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 1)) +
  labs(x = "minutes", y = "tortuosity") +
  facet_wrap(~stock, strip.position = "top") +
  scale_fill_manual(values=c("#e69f03", "#56b4e9")) +
  scale_color_manual(values=c("#e69f03", "#56b4e9")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text =  element_text(size = 30),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(face = "italic"),
        panel.background = element_rect(colour = "black", size=1))
ggsave("4-plots/tortuosity_facet_boxplot.png", width = 18, height = 6)
ggsave("4-plots/tortuosity_facet_boxplot.svg", width = 18, height = 6)
```

## Plot tortuosity smooth

```{r facet-smooth}
# Plot stocks separately using lines vertically
ggplot(datasets, aes(minute, tortuosity, color = sample)) +
  geom_smooth(span = 0.3, show.legend = FALSE, aes(fill = sample)) +
  facet_wrap(~stock, ncol = 2, strip.position = "top") +
  labs(x = "time after gastrulation (min)", y = "tortuosity") +
  scale_color_manual(values=c("#e69f03", "#56b4e9")) +
  scale_fill_manual(values=c("#e69f03", "#56b4e9")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text = element_text(size = 40),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(size = 45, face = "italic"),
        panel.background = element_rect(colour = "black", size=1),
        panel.spacing = unit(4, "lines"))
ggsave("4-plots/tortuosity_facet_smooth.png", width = 18, height = 6)
ggsave("4-plots/tortuosity_facet_smooth.svg", width = 18, height = 6)
```

## Plot combined tortuosity

```{r all-boxplot}
# Plot stocks together using boxplot
ggplot(datasets, aes(minute, tortuosity, fill = sample, group = interaction(minute, sample))) +
  geom_boxplot(aes(color = sample), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.7, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 1, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 1)) +
  labs(x = "minutes", y = "tortuosity") +
  scale_fill_manual(values=c("#e69f03", "#56b4e9")) +
  scale_color_manual(values=c("#e69f03", "#56b4e9")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text =  element_text(size = 30),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(face = "italic"),
        panel.background = element_rect(colour = "black", size=1))
ggsave("4-plots/tortuosity_all_boxplot.png", width = 18, height = 6)
ggsave("4-plots/tortuosity_all_boxplot.svg", width = 18, height = 6)
```

```{r all-smooth}
# Plot stocks together using lines
ggplot(datasets, aes(minute, tortuosity, color = sample)) +
  geom_smooth(span = 0.3, show.legend = FALSE, aes(fill = sample)) +
  labs(x = "time after gastrulation (min)", y = "tortuosity") +
  scale_color_manual(values=c("#e69f03", "#56b4e9")) +
  scale_fill_manual(values=c("#e69f03", "#56b4e9")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text = element_text(size = 40),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(size = 45, face = "italic"),
        panel.background = element_rect(colour = "black", size=1),
        panel.spacing = unit(4, "lines"))
ggsave("4-plots/tortuosity_all_smooth.png", width = 12, height = 6)
ggsave("4-plots/tortuosity_all_smooth.svg", width = 12, height = 6)
```

