---
title: "Folded area during ectopic folding"
author: "Bruno C. Vellutini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
creation: February 18, 2021
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, cache = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/Projects/Cephalic_furrow/7-Paper/1-analyses/folded-area")
library(ggplot2)
library(ggbeeswarm)
```

## Load measurements

```{r load}
# Load raw ROI measurements from ImageJ
results <- read.delim("results.txt")

# Remove slice number from the labels
results$Label <- gsub(":1", "", results$Label)

# Split label at "_s" to get the embryo name. sapply gets all first elements of the split.
results$Embryo <- sapply(strsplit(results$Label, "_s"), "[", 1)

# Remove "_CARE" from embryo name
results$Embryo <- gsub("_CARE", "", results$Embryo)

# Load sample info and merge with results
samples <- read.delim("samples.csv", sep = ",")
results <- merge(results, samples, by = "Label", all.x = TRUE)

# Load corrected area measurements for cartographic projections
corrected <- read.delim("corrected_results.txt", sep = "")
colnames(corrected) <- c("Label", "AreaCorr")

# Merge corrected area to results
results <- merge(results, corrected, by = "Label", all.x = TRUE)

# Transform data frame to order the stock for plotting
results <- transform(results, Stock=factor(Stock, levels = c("wt", "btd", "eve", "prd")))

# Quick fix to add type of fold
results$Type <- "EF"
results[results$Stock == "wt" & results$Position == "mid",]$Type <- "CF"
results[results$Stock == "btd" & results$Genotype == "heterozygote",]$Type <- "CF"
results[results$Stock == "eve" & results$Genotype == "heterozygote",]$Type <- "CF"
results[results$Stock == "prd" & results$Position == "mid",]$Type <- "CF"

# Transform data frame to order the stock for plotting
results <- transform(results, Sample=factor(Sample, levels = c("wildtype", "control", "mutant")))

# Sum total folded area corrected
areacorr <- aggregate(results$AreaCorr, list(results$Embryo), sum)
colnames(areacorr) <- c("Embryo", "AreaCorr")

# Sum total folded area corrected for CF
areacorr_cf <- aggregate(results[results$Type == "CF",]$AreaCorr, list(results[results$Type == "CF",]$Embryo), sum)
colnames(areacorr_cf) <- c("Embryo", "AreaCorrCF")

# Sum total folded area corrected for EF
areacorr_ef <- aggregate(results[results$Type == "EF",]$AreaCorr, list(results[results$Type == "EF",]$Embryo), sum)
colnames(areacorr_ef) <- c("Embryo", "AreaCorrEF")

# Count number of folds
nfold <- data.frame(table(results$Embryo))
colnames(nfold) <- c("Embryo", "Folds")

# Count number of CF folds
nfold_cf <- data.frame(table(results[results$Type == "CF",]$Embryo))
colnames(nfold_cf) <- c("Embryo", "CFs")

# Count number of EF folds
nfold_ef <- data.frame(table(results[results$Type == "EF",]$Embryo))
colnames(nfold_ef) <- c("Embryo", "EFs")

# Get sample information
embryos <- unique(results[, c("Embryo", "Stock", "Sample", "Genotype")])

# Merge datasets
total <- merge(embryos, areacorr, by = "Embryo", all.x = TRUE)
total <- merge(total, areacorr_cf, by = "Embryo", all.x = TRUE)
total <- merge(total, areacorr_ef, by = "Embryo", all.x = TRUE)
total <- merge(total, nfold, by = "Embryo", all.x = TRUE)
total <- merge(total, nfold_cf, by = "Embryo", all.x = TRUE)
total <- merge(total, nfold_ef, by = "Embryo", all.x = TRUE)

# Transform data frame to order the stock for plotting
total <- transform(total, Stock=factor(Stock, levels = c("wt", "btd", "eve", "prd")))
```

## Statistics for number of folds

```{r print-info}
# Print btd embryos
print_btd <- sprintf("btd: embryos=%s (het=%s, hom=%s), folds=%s (het=%s, hom=%s)",
        length(embryos[embryos$Stock == "btd",]$Embryo), # total embryos
        length(embryos[embryos$Genotype == "heterozygote" & embryos$Stock == "btd",]$Embryo), # het embryos
        length(embryos[embryos$Genotype == "homozygote" & embryos$Stock == "btd",]$Embryo), # hom embryos
        
        length(results[results$Stock == "btd",]$Label), # total folds
        length(results[results$Genotype == "heterozygote" & results$Stock == "btd",]$Label), # het folds
        length(results[results$Genotype == "homozygote" & results$Stock == "btd",]$Label) # het folds
        )

# Print eve embryos
print_eve <- sprintf("eve: embryos=%s (het=%s, hom=%s), folds=%s (het=%s, hom=%s)",
        length(embryos[embryos$Stock == "eve",]$Embryo), # total embryos
        length(embryos[embryos$Genotype == "heterozygote" & embryos$Stock == "eve",]$Embryo), # het embryos
        length(embryos[embryos$Genotype == "homozygote" & embryos$Stock == "eve",]$Embryo), # hom embryos
        
        length(results[results$Stock == "eve",]$Label), # total folds
        length(results[results$Genotype == "heterozygote" & results$Stock == "eve",]$Label), # het folds
        length(results[results$Genotype == "homozygote" & results$Stock == "eve",]$Label) # het folds
        )

# Print prd embryos
print_prd <- sprintf("prd: embryos=%s (het=%s, hom=%s), folds=%s (het=%s, hom=%s)",
        length(embryos[embryos$Stock == "prd",]$Embryo), # total embryos
        length(embryos[embryos$Genotype == "heterozygote" & embryos$Stock == "prd",]$Embryo), # het embryos
        length(embryos[embryos$Genotype == "homozygote" & embryos$Stock == "prd",]$Embryo), # hom embryos
        
        length(results[results$Stock == "prd",]$Label), # total folds
        length(results[results$Genotype == "heterozygote" & results$Stock == "prd",]$Label), # het folds
        length(results[results$Genotype == "homozygote" & results$Stock == "prd",]$Label) # het folds
        )

# Print wt embryos
print_wt <- sprintf(" wt: embryos=%s, folds=%s, ant=%s, mid=%s, post=%s",
        length(embryos[embryos$Stock == "wt",]$Embryo), # total embryos
        length(results[results$Stock == "wt",]$Label), # total folds
        length(results[results$Stock == "wt" & results$Position == "ant",]$Label), # anterior folds
        length(results[results$Stock == "wt" & results$Position == "mid",]$Label), # middle folds
        length(results[results$Stock == "wt" & results$Position == "post",]$Label) # posterior folds
        )

print_btd
print_eve
print_prd
print_wt

# Save nfolds output to files
capture.output(print_btd, print_eve, print_prd, print_wt, file = "nfolds.txt")
```

## Statistics for folded area

```{r print-stats}
print_stats <- function(dataframe, stock, type) {
  filter_df <- (dataframe$Stock == stock & dataframe$Type == type)
  df <- dataframe[filter_df,]
  df <- droplevels(df)

  # Define row
  row <- c(stock,
           type,
           mean(df$AreaCorr) / 1000,
           sd(df$AreaCorr) / 1000,
           length(df$AreaCorr)
           )
  
  # Summarize data
  print(sprintf("%s %s / area=%.3f±%.3f x 10^3 / n=%i",
                stock, type,
                mean(df$AreaCorr) / 1000,
                sd(df$AreaCorr) / 1000,
                length(df$AreaCorr)
                ))
  return(row)
}

# Save stats to data frame
stats <- data.frame()

# Bind row by row
stats <- rbind(stats, print_stats(results, "wt", "CF"))
stats <- rbind(stats, print_stats(results, "wt", "EF"))
stats <- rbind(stats, print_stats(results, "btd", "CF"))
stats <- rbind(stats, print_stats(results, "btd", "EF"))
stats <- rbind(stats, print_stats(results, "eve", "CF"))
stats <- rbind(stats, print_stats(results, "eve", "EF"))
stats <- rbind(stats, print_stats(results, "prd", "CF"))
stats <- rbind(stats, print_stats(results, "prd", "EF"))

# Add column names
colnames(stats) <- c("stock", "type", "mean", "sd", "n")

# Convert columns to numeric
stats[, 3:5] <- apply(stats[, 3:5], 2, as.numeric)

# Round up
stats[, 3:4] <- round(stats[, 3:4], digits=1)

# Write table to file
write.table(format(stats, digits=2), file = "stats.txt", quote = FALSE, row.names = FALSE, sep = "\t")
```

## Total folded area per embryo

Plot the total area of folded tissue per embryo of different genotypes.

```{r total-area-per-embryo}
ggplot(total, aes(Stock, AreaCorr, fill = Genotype)) +
  geom_boxplot(aes(color = Genotype), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.7, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 3, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 6)) +
  scale_y_continuous(labels = function(x) x / 1000) +
  labs(x = "stocks", y = expression(paste("total folded area per embryo ", (µm^2)~x~10^3))) +
  facet_grid(cols = vars(Stock), scales = "free_x") +
  scale_fill_manual(values=c("#56b4e9", "#e69f03", "#cc79a7")) +
  scale_color_manual(values=c("#56b4e9", "#e69f03", "#cc79a7")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text =  element_text(size = 35),
        strip.background = element_blank(),
        panel.background = element_rect(colour = "black", size=1),
        )
ggsave("4-plots/total-area-per-embryo.png", width = 12, height = 4)
ggsave("4-plots/total-area-per-embryo.svg", width = 12, height = 4)
```

## Area of individual ectopic folds

```{r individual-area-per-ectopic-fold}
ggplot(results[results$Stock != "prd" & results$Type == "EF",], aes(Sample, AreaCorr, fill = Sample)) +
  geom_boxplot(aes(color = Sample), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.7, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 3, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 2.5)) +
  scale_y_continuous(labels = function(x) x / 1000) +
  labs(x = "stocks", y = expression(paste("area ", (µm^2)~x~10^3))) +
  scale_fill_manual(values=c("#56b4e9", "#e69f03", "#cc79a7")) +
  scale_color_manual(values=c("#56b4e9", "#e69f03", "#cc79a7")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text =  element_text(size = 35),
        strip.background = element_blank(),
        panel.background = element_rect(colour = "black", size=1)
        )
ggsave("4-plots/individual-area-per-ectopic-fold.png", width = 12, height = 6)
ggsave("4-plots/individual-area-per-ectopic-fold.svg", width = 12, height = 6)
```

## Area of individual ectopic folds per position

```{r area-individual-folds-per-position}
ggplot(results, aes(Stock, AreaCorr, fill = Genotype)) +
  geom_boxplot(aes(color = Genotype), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.7, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 3, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 3)) +
  scale_y_continuous(labels = function(x) x / 1000) +
  labs(x = "stocks", y = expression(paste("area of individual folds ", (µm^2)~x~10^3))) +
  scale_fill_manual(values=c("#56b4e9", "#e69f03", "#cc79a7")) +
  scale_color_manual(values=c("#56b4e9", "#e69f03", "#cc79a7")) +
  facet_grid(cols = vars(Position), scales = "free") +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text = element_text(size = 30),
        strip.background = element_blank(),
        panel.background = element_rect(colour = "black", size=1),
        axis.text.x = element_text(face = "italic"),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        )
ggsave("4-plots/individual-area-per-position.png", width = 9, height = 4)
ggsave("4-plots/individual-area-per-position.svg", width = 9, height = 4)
```

## Area of individual folds per type

```{r individual-area-per-type}
ggplot(results, aes(Type, AreaCorr, fill = Genotype)) +
  geom_boxplot(aes(color = Genotype), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.7, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 3, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 6)) +
  scale_y_continuous(labels = function(x) x / 1000) +
  labs(x = "stocks", y = expression(paste("area ", (µm^2)~x~10^3))) +
  facet_grid(cols = vars(Stock), scales = "free_x") +
  scale_fill_manual(values=c("#56b4e9", "#e69f03", "#cc79a7")) +
  scale_color_manual(values=c("#56b4e9", "#e69f03", "#cc79a7")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text =  element_text(size = 35),
        strip.background = element_blank(),
        panel.background = element_rect(colour = "black", size=1),
        )
ggsave("4-plots/individual-area-per-type.png", width = 12, height = 4)
ggsave("4-plots/individual-area-per-type.svg", width = 12, height = 4)
```
