---
title: "Variation of cell area after mitosis"
author: "Bruno C. Vellutini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
creation: February 11, 2021
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, cache = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/Projects/Cephalic_furrow/7-Paper/1-analyses/cell-area-post-mitosis")
library(knitr)
library(ggplot2)
library(ggbeeswarm)
```

## Load data Experiment metadata

I edited the `Results.txt` file in a spreadsheet to facilitate plotting before
loading the data.

```{r load}
results <- read.csv("cellarea_E10.csv")
levels(results$Time) <- c("T1", "T2", "T3")
```

## Variation in the apical area of individual cells

```{r cellarea}
ggplot(results, aes(Time, Area)) +
  geom_boxplot(show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.7, position = position_dodge(width = 1.0)) +
  geom_point(aes(color = Lineage), alpha = 0.8, size = 5, show.legend = TRUE, position = position_beeswarm(priority = "descending", dodge.width = 0.5, cex = 1)) +
  labs(x = "time", y = expression(paste("area x ", 10^3, " ", "(", px^2, ")"))) +
  scale_y_continuous(labels = function(x) x / 1000) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text =  element_text(size = 30),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(face = "italic"),
        panel.background = element_rect(colour = "black", size=1))
ggsave("3-plots/apical-area-per-cell.png", width = 12, height = 6)
ggsave("3-plots/apical-area-per-cell.svg", width = 12, height = 6)
```

## Summary

```{r summary}
rows <- c("Individual Cell Area", "Total Cell Area", "Relative Cell Area", "Relative Total Area")
T1 <- c(mean(results[results$Time == "t1", "Area"]),
        mean(results[results$Time == "t1", "TotalArea"]),
        mean(results[results$Time == "t1", "NormArea"]),
        mean(results[results$Time == "t1", "NormTotalArea"]))
T2 <- c(mean(results[results$Time == "t2", "Area"]),
        mean(results[results$Time == "t2", "TotalArea"]),
        mean(results[results$Time == "t2", "NormArea"]),
        mean(results[results$Time == "t2", "NormTotalArea"]))
T3 <- c(mean(results[results$Time == "t3", "Area"]),
        mean(results[results$Time == "t3", "TotalArea"]),
        mean(results[results$Time == "t3", "NormArea"]),
        mean(results[results$Time == "t3", "NormTotalArea"]))
sumtable <- data.frame(T1, T2, T3, row.names = rows)

# Round up
sumtable[1:2,] <- round(sumtable[1:2,], digits=0)
sumtable[3:4,] <- round(sumtable[3:4,], digits=2)

# Write table to file
write.table(format(sumtable, digits=2), file = "stats.txt", quote = FALSE, row.names = FALSE, sep = "\t")
print(sumtable)
```
