---
title: "Cephalic furrow laser ablations"
author: "Bruno C. Vellutini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
creation: April 06, 2021
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, cache = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/Projects/Cephalic_furrow/7-Paper/1-analyses/ablations")
library(ggplot2)
library(ggbeeswarm)
```

## Load measurements

```{r load}
# Load raw ROI measurements from ImageJ
ablations <- read.csv("ablation-data.csv", stringsAsFactors = TRUE)
levels(ablations$Stage) <- c("early", "mid", "late")
```

## Summarize by stage and position

```{r summary}
print_stats <- function(dataframe, stage, position = NULL, distance = NULL) {
  if (!is.null(distance)) {
    filter_df <- (dataframe$Stage == stage & dataframe$Position == position & dataframe$Distance == distance)
  } else if (!is.null(position)) {
    filter_df <- (dataframe$Stage == stage & dataframe$Position == position)
    distance <- "all"
  } else {
    filter_df <- (dataframe$Stage == stage)
    position <- "both"
    distance <- "all"
  }
  
  df <- dataframe[filter_df,]
  df <- droplevels(df)

  # Define row
  row <- c(stage,
           position,
           distance,
           mean(df$Velocity),
           sd(df$Velocity),
           length(df$Velocity),
           length(unique(df$Embryo))
           )

  return(row)
}

# Save stats to data frame
stats <- data.frame()

# Bind row by row
stats <- rbind(stats, print_stats(ablations, "early"))
stats <- rbind(stats, print_stats(ablations, "mid"))
stats <- rbind(stats, print_stats(ablations, "late"))
stats <- rbind(stats, print_stats(ablations, "early", "anterior"))
stats <- rbind(stats, print_stats(ablations, "early", "posterior"))
stats <- rbind(stats, print_stats(ablations, "mid", "anterior"))
stats <- rbind(stats, print_stats(ablations, "mid", "posterior"))
stats <- rbind(stats, print_stats(ablations, "late", "anterior"))
stats <- rbind(stats, print_stats(ablations, "late", "posterior"))

# Add column names
colnames(stats) <- c("stage", "position", "distance", "mean", "sd", "n_cuts", "n_embryos")

# Convert columns to numeric
stats[, 4:7] <- apply(stats[, 4:7], 2, as.numeric)

# Round up
stats[, 4:5] <- round(stats[, 4:5], digits=10)

# Write table to file
write.table(format(stats, digits=10), file = "stats.txt", quote = FALSE, row.names = FALSE, sep = "\t")
print(stats)
```

## Plot velocity by stage

```{r recoil-stage}
ggplot(ablations, aes(Stage, Velocity)) +
  geom_boxplot(aes(color = "#e69f03", fill = "#e69f03"), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.9, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 3, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 2)) +
  labs(x = "stage", y = "velocity (µm/s)") +
  scale_fill_manual(values=c("#e69f03", "#56b4e9")) +
  scale_color_manual(values=c("#e69f03", "#56b4e9")) +
  scale_y_continuous(limits = c(0, 0.25)) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text = element_text(size = 30),
        panel.background = element_rect(colour = "black", size=1))
ggsave("3-plots/recoil-stage.png", width = 14, height = 7)
ggsave("3-plots/recoil-stage.svg", width = 14, height = 7)
```

## Plot velocity by stage

```{r recoil-stage-position}
ggplot(ablations, aes(Position, Velocity, fill = Position)) +
  geom_boxplot(aes(color = Position), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.9, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 3, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 2)) +
  labs(x = "stage", y = "velocity (µm/s)") +
  scale_fill_manual(values=c("#e69f03", "#56b4e9")) +
  scale_color_manual(values=c("#e69f03", "#56b4e9")) +
  facet_wrap(~Stage) +
  scale_y_continuous(limits = c(0, 0.25)) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text = element_text(size = 45),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(size = 55),
        panel.background = element_rect(colour = "black", size=1))
ggsave("3-plots/recoil-stage-position.png", width = 14, height = 7)
ggsave("3-plots/recoil-stage-position.svg", width = 14, height = 7)
```

## Calculate means and distance classes

```{r means}
# Mean of recoil velocity per embryo/cut
embryo_mean <- aggregate(ablations$Velocity, list(ablations$Embryo), mean)
colnames(embryo_mean) <- c("Embryo", "Velocity")

# Standard deviation of CF length per embryo
embryo_sd <- aggregate(ablations$Velocity, list(ablations$Embryo), sd)
colnames(embryo_sd) <- c("Embryo", "SD")

# Get sample information
samples <- unique(ablations[, c("Embryo", "Stage", "Position", "Distance")])

# Merge datasets
means <- merge(samples, embryo_mean, by = "Embryo", all.x = TRUE)
means <- merge(means, embryo_sd, by = "Embryo", all.x = TRUE)

# Establish near (5-20µm) and far (25-40µm) distance classes.
means[means$Distance <= 20 & means$Distance > 0,]$Distance <- 20
means[means$Distance <= 40 & means$Distance > 20,]$Distance <- 40
means[means$Distance >= -20 & means$Distance < 0,]$Distance <- -20
means[means$Distance >= -40 & means$Distance < -20,]$Distance <- -40
means$Distance <- as.factor(means$Distance)

# Save stats to data frame
dists <- data.frame()

# Bind row by row
dists <- rbind(dists, print_stats(means, "early", "anterior", "-40"))
dists <- rbind(dists, print_stats(means, "early", "anterior", "-20"))
dists <- rbind(dists, print_stats(means, "early", "posterior", "20"))
dists <- rbind(dists, print_stats(means, "early", "posterior", "40"))
dists <- rbind(dists, print_stats(means, "mid", "anterior", "-40"))
dists <- rbind(dists, print_stats(means, "mid", "anterior", "-20"))
dists <- rbind(dists, print_stats(means, "mid", "posterior", "20"))
dists <- rbind(dists, print_stats(means, "mid", "posterior", "40"))
dists <- rbind(dists, print_stats(means, "late", "anterior", "-40"))
dists <- rbind(dists, print_stats(means, "late", "anterior", "-20"))
dists <- rbind(dists, print_stats(means, "late", "posterior", "20"))
dists <- rbind(dists, print_stats(means, "late", "posterior", "40"))

# Add column names
colnames(dists) <- c("stage", "position", "distance", "mean", "sd", "n_cuts", "n_embryos")

# Convert columns to numeric
dists[, 4:7] <- apply(dists[, 4:7], 2, as.numeric)

# Round up
dists[, 4:5] <- round(dists[, 4:5], digits=10)

# Write table to file
write.table(format(dists, digits=10), file = "means.txt", quote = FALSE, row.names = FALSE, sep = "\t")
print(dists)
```

## Plot recoil means by distance classes

```{r means-stage-classes}
ggplot(means, aes(Distance, Velocity, group = Distance, fill = Position)) +
  geom_boxplot(aes(color = Position), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.8, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 5, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 4)) +
  scale_y_continuous(limits = c(-0.008, 0.25)) +
  facet_wrap(~Stage) +
  labs(x = "stage", y = "velocity (µm/s)") +
  scale_fill_manual(values=c("#009966", "#cc79a7")) +
  scale_color_manual(values=c("#009966", "#cc79a7")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text = element_text(size = 45),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(size = 55),
        panel.background = element_rect(colour = "black", size=1))
ggsave("3-plots/recoil-stage-distance.png", width = 14, height = 7)
ggsave("3-plots/recoil-stage-distance.svg", width = 14, height = 7)
```

