---
title: "Fold statistics"
author: "Bruno C. Vellutini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
creation: November 30, 2022
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, cache = FALSE)
knitr::opts_knit$set(root.dir = "~/Dropbox/Projects/Cephalic_furrow/7-Manuscript/1-analyses/fold-stats")
library(ggplot2)
```

## Import datasets

```{r import}
# Load sample info and merge with results
area_results <- read.delim("../folded-area/combined_results.csv", sep = ",")
depth_results <- read.delim("../fold-depth/combined_results.csv", sep = ",")

# Remove discarded folds marked as FALSE in area dataset
area_results <- area_results[area_results$Discard == FALSE, ]

# Subset only relevant columns and merge
fold_cols <- c("Embryo", "Stock", "Genotype", "View", "Side", "Fold", "Position", "Type")
area_results <- area_results[, fold_cols]
depth_results <- depth_results[, fold_cols]
folds <- rbind(area_results, depth_results)

# Transform data frame to order the stock for plotting
folds$Stock <- factor(folds$Stock, levels = c("wt", "btd", "eve", "prd", "stg", "btd-stg"))
folds$Genotype <- factor(folds$Genotype, levels = c("wildtype", "heterozygote", "homozygote", "double heterozygote", "btd homozygote", "stg homozygote", "double homozygote"))
folds$Type <- factor(folds$Type, levels = c("CF", "EF"))
folds$Position <- factor(folds$Position, levels = c("ant", "mid", "post"))


folds <- folds[order(folds$Stock, folds$Genotype, folds$Position, folds$Type),]
rownames(folds) <- 1:nrow(folds)

# Save data frame to file
write.csv(folds, file = "folds.csv", row.names = FALSE)
```

## Frequency of folding per genotype, fold type, and position

```{r fold-frequency}

stats <- data.frame()

for (stock in unique(folds$Stock)) {
  
  print(stock)
  
  # Define data frame for stock
  df_stock <- folds[folds$Stock == stock, ]
  
  # Total embryos per stock
  n_stock <- length(unique(df_stock$Embryo))
  
  # Define stock's genotypes
  genotypes <- unique(df_stock$Genotype)
  
  for (genotype in genotypes) {
    
    print(genotype)
    
    # Define data frame for genotype
    df_genotype <- df_stock[df_stock$Genotype == genotype, ]
    
    # Total embryos per genotype
    n_genotype <- length(unique(df_genotype$Embryo))
    
    # Percentage embryos per genotype
    pct_genotype <- round((n_genotype / n_stock) * 100, digits = 1)
    
    # Total embryos with a fold
    n_with_fold <- length(unique(df_genotype[df_genotype$Fold == TRUE, ]$Embryo))
    
    # Percentage embryos with a fold
    pct_with_fold <- round((n_with_fold / n_genotype) * 100, digits = 1)
    
    # Define foldtypes for true folds
    foldtypes <- unique(df_genotype[df_genotype$Fold == TRUE, ]$Type)
    
    for (foldtype in foldtypes) {
      
      print(foldtype)
      
      # Define data frame for foldtype
      df_foldtype <- df_genotype[df_genotype$Type == foldtype & df_genotype$Fold == TRUE, ]
      
      # Total embryos per foldtype
      n_foldtype <- length(unique(df_foldtype$Embryo))
      
      # Percentage embryos per foldtype
      pct_foldtype <- round((n_foldtype / n_genotype) * 100, digits = 1)
      
      # Define positions for folds
      positions <- unique(df_foldtype$Position)
      
      for (position in positions) {
        
        print(position)
        
        # Define data frame for fold position
        df_position <- df_foldtype[df_foldtype$Position == position, ]
        
        # Total embryos per position
        n_position <- length(unique(df_position$Embryo))
        
        # Percentage embryos per position
        pct_position <- round((n_position / n_foldtype) * 100, digits = 1)
        
        # Create rows for output data frame
        row <- c(
          stock = stock,
          n_stock = n_stock,
          genotype = genotype,
          n_genotype = n_genotype,
          pct_genotype = pct_genotype,
          n_with_fold = n_with_fold,
          pct_with_fold = pct_with_fold,
          foldtype = foldtype,
          n_foldtype = n_foldtype,
          pct_foldtype = pct_foldtype,
          position = position,
          n_position = n_position,
          pct_position = pct_position
          )
        
        # Bind rows to stats data frame
        stats <- rbind(stats, as.data.frame(t(row)))
        
      }
    }
  }
}

# Transform data frame to order the stock for plotting
stats$stock <- factor(stats$stock, levels = c("wt", "btd", "eve", "prd", "stg", "btd-stg"))
stats$genotype <- factor(stats$genotype, levels = c("wildtype", "heterozygote", "homozygote", "double heterozygote", "btd homozygote", "stg homozygote", "double homozygote"))
stats$foldtype <- factor(stats$foldtype, levels = c("CF", "EF"))
stats$position <- factor(stats$position, levels = c("ant", "mid", "post"))

# Order
stats <- stats[order(stats$stock, stats$genotype, stats$foldtype, stats$position),]
rownames(stats) <- 1:nrow(stats)

# Save stats data frame to file
write.csv(stats, file = "stats.csv", row.names = FALSE)
stats
```

## Plot proportion of fold types (bar plot)

```{r plot-percentage-events-bar}

ggplot(folds, aes(Genotype, fill = Type)) +
  geom_bar(alpha = 0.5, position = position_fill(reverse = TRUE), stat = "count") +
  labs(x = "genotype", y = "fold type proportion") +
  #geom_bar(position = position_stack(reverse = TRUE), stat = "count") +
  #labs(x = "genotype", y = "folds by type") +
  facet_grid(cols = vars(Stock), scales = "free") +
  scale_fill_manual(values=c("#56b4e9", "#e69f03")) +
  scale_color_manual(values=c("#56b4e9", "#e69f03")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 10),
        axis.text.y=element_blank(),
        strip.background = element_blank(),
        panel.background = element_rect(colour = "black", linewidth = 1)
        )


ggsave("2-plots/datalong-bar-pct_event-vs-condition.png", width = 10, height = 4)
ggsave("2-plots/datalong-bar-pct_event-vs-condition.svg", width = 10, height = 4)

```


## Plot individual fold depth by stocks

```{r plot-individual-depth}

ggplot(folds, aes(Type)) +
  geom_histogram()

# Plot stocks separately
ggplot(folds, aes(Genotype, Length, fill = Genotype, shape = Type)) +
  geom_boxplot(aes(color = Genotype), show.legend = FALSE, alpha = 0.5, outlier.shape = NA, width = 0.7, position = position_dodge(width = 1.0)) +
  geom_point(alpha = 0.8, size = 3, show.legend = FALSE, position = position_beeswarm(priority = "descending", dodge.width = 1.0, cex = 4)) +
  labs(x = "mutants", y = "depth") +
  facet_wrap(~Stock, strip.position = "top") +
  scale_fill_manual(values=c("#56b4e9", "#e69f03")) +
  scale_color_manual(values=c("#56b4e9", "#e69f03")) +
  theme_classic(base_family = "DejaVu Sans") +
  theme(text =  element_text(size = 30),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(face = "italic"),
        panel.background = element_rect(colour = "black", linewidth = 1))
ggsave("3-plots/depth_facet.png", width = 12, height = 6)
ggsave("3-plots/depth_facet.svg", width = 12, height = 6)

```

## Plot overview

```{r plot}
ggplot(folds, aes(Type, fill = Genotype)) +
  geom_histogram(stat = "count") +
  scale_fill_manual(values=c("#cc79a7", "#56b4e9", "#e69f03")) +
  scale_color_manual(values=c("#cc79a7", "#56b4e9", "#e69f03")) +
  facet_grid(cols = vars(Stock), scales = "free_y") +
  theme_classic() +
  theme(text = element_text(size = 35),
        strip.background = element_blank(),
        panel.background = element_rect(colour = "black", size=1)
        )
ggsave("folds-average.png", width = 20, height = 7)
ggsave("folds-average.svg", width = 20, height = 7)
```